inherit_from: .rubocop_todo.yml

# This configuration does not exclude known offenders
# Environments: Local(commandline, code editor)

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - log/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.1

# Metrics
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 250

# RSpec
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleExpectations:
  Max: 10
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - but
    - and
RSpec/DescribedClass:
  SkipBlocks: true
RSpec/FilePath:
  CustomTransform:
    FFaker: ffaker
RSpec/SharedExamples:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled : false
RSpec/NamedSubject:
  Enabled : false

# Style
Style/DateTime:
  Enabled: true
Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 4
Style/NumericLiterals:
  Enabled: false
Style/CommentAnnotation:
  Enabled: true
  Keywords:
    - DEPRECATED
    - EPHEMERAL
    - FIXME
    - HACK
    - IMPORTANT
    - NOTE
    - OPTIMIZE
    - REMOVE_ME
    - REVIEW
    - SECURITY
    - TODO
    - WARNING
Style/RegexpLiteral:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
